project_id = "brukpbahpxhnsjnywywp"

[functions.initiate-call]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.save-call-response]
verify_jwt = false

[functions.process-batch]
verify_jwt = false

[functions.elevenlabs-webhook]
verify_jwt = false

[functions.ai-health-analysis]
verify_jwt = false

[functions.extract-patient-from-pdf]
verify_jwt = false
